name: Build Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Prepare pyz
        run: |
          mkdir -p build/ext

          cp main_pyz.py build/__main__.py
          cp installer.py build/ext/
          cp updater.py build/ext/
          cp wrapper.py build/ext/
          cp ventoy.cmd build/ext/
          touch build/ext/__init__.py

      - name: Build normal pyz
        run: |
          python -m zipapp build \
            -o ventoy-wrapper.pyz \
            --compress

      - name: Build package pyz
        run: |
          sed -i 's/^INSTALLER_MANAGED = True$/INSTALLER_MANAGED = False/' build/ext/updater.py

          python -m zipapp build \
            -o ventoy-wrapper-standalone.pyz \
            --compress

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ventoy-wrapper.pyz
            ventoy-wrapper-standalone.pyz
